MVCDemoApp6/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MVCDemoApp6.Models
{
    public class Employee
    {
        [Required(ErrorMessage = "EmpId is compulsory field")]
        [RegularExpression(@"[0-9]{4}",ErrorMessage ="Enter four digit EMployee Id")]
        public int? EmpId { get; set; }

        [Required(ErrorMessage = "EmpName is compulsory field")]
        [StringLength(10, ErrorMessage = "Maximum EmpName length is 10 characters")]
        public string EmpName { get; set; }

        [Required(ErrorMessage = "Salary is compulsory field")]
        public double? Salary { get; set; }
    }
}

MVCDemoApp6/Models/ErrorViewModel.cs
using System;

namespace MVCDemoApp6.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCDemoApp6/Models/RegisteredEntries.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCDemoApp6.Models
{
    public class RegisteredEntries
    {
        
        [Required(ErrorMessage = "Please enter your name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please enter your email")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Email { get; set; }

        
        [Required(ErrorMessage = "Please enter your phone number")]
        [RegularExpression(@"^([0-9]{10})$", ErrorMessage = "Invalid Mobile Number.")]
        public string Phone { get; set; }


        [Required(ErrorMessage = "Please specify whether you'll attend")]
        public string WillAttend { get; set; }
    }

}

MVCDemoApp6/Controllers/AssignmentController.cs
using Microsoft.AspNetCore.Mvc;
using MVCDemoApp6.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVCDemoApp6.Controllers
{
    public class AssignmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult RegistrationForm()
        {
            return View(new RegisteredEntries());
        }

        public IActionResult RegisterPerson(RegisteredEntries newEntry, string confirmation)
        {
            if (ModelState.IsValid)
            {
      
                return View(newEntry);
            }
            
            if (confirmation.Equals("true"))
            {
                ViewBag.message = "Thanks for showing your interest for attending seminar";
                
            }
            else
            {
                ViewBag.message = "Sorry, but you are not registered for attending the seminar";
            }
            
            return View("RegisterPerson", newEntry);

        }
    }
}

MVCDemoApp6/Controllers/DataPersistantDemoController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MVCDemoApp6.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading.Tasks; 

namespace MVCDemoApp6.Controllers
{
    public class DataPersistantDemoController : Controller
    {
        public IConfiguration Configuration { get; }

        public DataPersistantDemoController(IConfiguration _configuration)
        {
            Configuration = _configuration;
        }
        public IActionResult Index()
        {
            ViewBag.data = Configuration["customkey"];
            return View();
        }

        public IActionResult SessionDemo()
        {
            //create session values
            //HttpContext.Session.SetString(key, value);
            HttpContext.Session.SetString("message", "Session test");
            HttpContext.Session.SetInt32("count", 5);

            HttpContext.Session.SetString("dateobj", JsonSerializer.Serialize(DateTime.Now));

            Employee employee = new Employee() { EmpId = 101, EmpName = "Priyanka", Salary = 30000 };
            string empserializedata = JsonSerializer.Serialize(employee);
            HttpContext.Session.SetString("empobj", empserializedata);

            return RedirectToAction("GetSessionvalues");
        }

        public IActionResult GetSessionValues()
        {
            //read session value
            ViewBag.message = HttpContext.Session.GetString("message");
            ViewBag.count = HttpContext.Session.GetInt32("count");

            var dateobj = HttpContext.Session.GetString("dateobj");
            ViewBag.date = JsonSerializer.Deserialize<DateTime>(dateobj);

            string emp = HttpContext.Session.GetString("empobj");
            Employee empobj = JsonSerializer.Deserialize<Employee>(emp);
            ViewBag.emp = empobj;

            return View();
        }

        public IActionResult WriteCookies(string setting,string settingValue,bool isPersistant)
        {
            if(isPersistant)
            {
                CookieOptions options = new CookieOptions();
                options.Expires = DateTime.Now.AddDays(1);
                Response.Cookies.Append(setting, settingValue, options);
            }

            else
            {
                Response.Cookies.Append(setting, settingValue);
            }

            ViewBag.Message = "Cookie written successfully";
            return View("Index");
        }

        public IActionResult ReadCookies()
        {
            ViewBag.FontName = Request.Cookies["fontName"];
            ViewBag.FontSize = Request.Cookies["fontSize"];
            ViewBag.Color = Request.Cookies["color"];

            if(string.IsNullOrEmpty(ViewBag.FontName))
            {
                ViewBag.FontName = "Arial";
            }
            if (string.IsNullOrEmpty(ViewBag.FontSize))
            {
                ViewBag.FontSize = "22px";
            }
            if (string.IsNullOrEmpty(ViewBag.Color))
            {
                ViewBag.Color = "Black";
            }
            return View();
        }
    }
}

MVCDemoApp6/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCDemoApp6.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCDemoApp6.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Route("Home/Greet/{name?}")]
        public IActionResult Greet(string name)
        {
            //return Content("Welcome to MVC");
            //return View("Greet1"); ///if our view has different name then use parametrized view() and pass name of view
            ViewBag.wish = "Hello " +name;
            return View();
        }

        public IActionResult GetData(int id)
        {
            ViewBag.message = "Id = " + id;
            return View();
        }


        //[HttpPost("Home/AddNumbers/{first:int:range(1,100)}/{second:int?}")]
        [Route("[controller]/[action]/{first:int:range(1,100)}/{second:int?}")]
        //[Route("Home/AddNumbers/{first:int:range(1,100)}/{second:int?}")]
        public  IActionResult AddNumbers(int first,int second)
        {
            int result = first + second;
            ViewBag.add = $"{first}+{second}={result}";
            return View();
        }

        public IActionResult ModelDemo()
        {
            Employee employee = new Employee { EmpId = 1, EmpName = "Priya", Salary = 10000 };
            //ViewBag.emp = employee;
            ViewData["emp"] = employee;
            return View();
        }

        public IActionResult EmployeeForm()
        {
            return View(new Employee());
        }

        public IActionResult DisplayEmployeeData(Employee employee)
        {
            if(ModelState.IsValid)
            {
                return View(employee);
            }

            return View("Employee",employee);
        }
        
    }
}

MVCDemoApp6/Views/Assignment/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

    <div class="container">
        <h1 class="text-center text-warning">Welcome to Mindfullness & Meditation Session</h1>
        <img class="rounded mx-auto d-block" src="~/lib/Emotional.jpg" width="400" height="300" />
        <p class="text-center text-success">When we meditate, we inject far-reaching and long-lasting benefits into our lives: We lower our stress levels,
        we get to know our pain, we connect better, we improve our focus, and we're kinder to ourselves. Let us walk you 
        through the basics in our new mindful guide on how to meditate.</p>
        <a class="text-lg-center text-white bg-dark" asp-area="" asp-controller="Assignment" asp-action="RegistrationForm">Click here to Register</a>
    </div>

MVCDemoApp6/Views/Assignment/RegisterPerson.cshtml
@model RegisteredEntries
@{
    ViewData["Title"] = "RegisterPerson";
}

<h1 class="text-center text-success" >Thank you @Model.Name</h1>
<br />
<h4 class="text-center">@ViewBag.message</h4>

MVCDemoApp6/Views/Assignment/RegistrationForm.cshtml
@model RegisteredEntries
@{
    ViewData["Title"] = "RegistrationForm";
}
@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<h1 class="text-primary">RegistrationForm</h1>

    <form asp-controller="Assignment" asp-action="RegisterPerson" method="post">
        @*<div asp-validation-summary="All" class="text text-danger"></div>*@
        Name:<input type="text" asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text text-danger"></span>
        <br />
        Email:<input type="text" asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text text-danger"></span>
        <br />
        Phone:<input type="text" asp-for="Phone" class="form-control" />
        <span asp-validation-for="Phone" class="text text-danger"></span>
        <br />
        WillAttend:<select asp-for="WillAttend" class="form-control" name="confirmation">
            <option value="" selected disabled hidden>Confirmation</option>
            <option value="true">Yes, I'll be there</option>
            <option value="false">No, I can't come</option>
        </select>
        <span asp-validation-for="WillAttend" class="text text-danger"></span>
        <br />
        <button type="submit" class="btn btn-success">Register</button>

     </form>

MVCDemoApp6/Views/DataPersistantDemo/GetSessionValues.cshtml
@{
    ViewData["Title"] = "GetSessionValues";
}

<h1>GetSessionValues</h1>

@ViewBag.message
<br />
@ViewBag.count
<br />
@ViewBag.date
<br />

<hr />
@ViewBag.emp.EmpId
<br />
@ViewBag.emp.EmpName
<br />
@ViewBag.emp.Salary
<br />

MVCDemoApp6/Views/DataPersistantDemo/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h3>@ViewBag.data</h3>
<hr/>

<h1>Specify your preferences:</h1>
<form asp-action="WriteCookies" asp-controller="DataPersistantDemo">
    <select name="setting">
        <option value="fontName">Font Name</option>
        <option value="fontSize">Font Size</option>
        <option value="color">Color</option>
    </select>
    <input type="text" name="settingValue" />
    <input type="checkbox" name="isPersistant" value="true"/>Is Persistent?
    <input type="submit" name="Write Cookie" />

</form>
<h4>@ViewBag.Message</h4>
<h4>
    <a asp-action="ReadCookies" asp-controller="DataPersistantDemo">
        Read Cookies
    </a>
</h4>

MVCDemoApp6/Views/DataPersistantDemo/ReadCookies.cshtml
@{
    ViewData["Title"] = "ReadCookies";
}

<h1>ReadCookies</h1>
<div style="font-family:'@ViewBag.FontName';
     font-size:@ViewBag.FontSize;
     color:@ViewBag.Color">
    Hello World!
</div>

MVCDemoApp6/Views/Home/AddNumbers.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddNumbers</title>
</head>
<body>
    <h3>@ViewBag.add</h3>
</body>
</html>

MVCDemoApp6/Views/Home/DisplayEmployeeData.cshtml
@model Employee
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DisplayEmployeeData</title>
</head>
<body>
    <h3>Employee Data</h3>

    @Model.EmpId<br />
    @Model.EmpName<br />
    @Model.Salary<br />

</body>
</html>

MVCDemoApp6/Views/Home/EmployeeForm.cshtml
@model Employee
@{
    ViewData["Title"] = "EmployeeForm";
}
@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<h1 class="text-warning">EmployeeForm</h1>
<form asp-controller="Home" asp-action="DisplayEmployeeData" method="post" class="container">
    <div asp-validation-summary="All" class="text text-danger"></div>
    EmpID:<input type="text" asp-for="EmpId" class="form-control" />
    <span asp-validation-for="EmpId"></span>
    <br />
    EmpName:<input type="text" asp-for="EmpName" class="form-control" />
    <span asp-validation-for="EmpName"></span>
    <br />
    Salary:<input type="text" asp-for="Salary" class="form-control" />
    <span asp-validation-for="Salary"></span>
    <br />
    <button type="submit" class="btn btn-success">Submit</button>

</form>

MVCDemoApp6/Views/Home/GetData.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetData</title>
</head>
<body>
    <h3>
        @ViewBag.message
    </h3>
</body>
</html>

MVCDemoApp6/Views/Home/Greet.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Greet</title>
</head>
<body>
    <h2>Welcome to MVC view</h2>
    <h3>@ViewBag.wish</h3>
    
</body>
</html>

MVCDemoApp6/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCDemoApp6/Views/Home/ModelDemo.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ModelDemo</title>
</head>
<body>
    <h3>Employee Data</h3>
    @*@ViewBag.emp.EmpId<br />
    @ViewBag.emp.EmpName<br />
    @ViewBag.emp.Salary<br />*@

    @{ 
        Employee emp = ViewData["emp"] as Employee;
    }
    @emp.EmpId<br/>
    @emp.EmpName<br/>
    @emp.Salary<br/>
</body>
</html>

MVCDemoApp6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDemoApp6</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDemoApp6</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="DataPersistantDemo" asp-action="Index">DataPersistantDemo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="DataPersistantDemo" asp-action="SessionDemo">Session</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area=""
                               asp-controller="Assignment" asp-action="Index">Seminar</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MVCDemoApp6 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>